### ISSUE TITLE
Latest Release 112.0.0 Konstruction and logistics now missing in assembly buildings

### ISSUE THREAD

**Issue by fbelter** [UmbraSpaceIndustries/USITools#159]
When I installed the latest release, Konstruction and Logistics are now missing.

**Comment by tjdeckard** [comment]
We're in the process of migrating to an automated build and release system. So 112.0.0 isn't an official release yet even though it looks like one. Unfortunately there isn't a way (that I know of) to make sure the automated system is able to make official releases without allowing it to make an official release. I'm curious now... how did you discover that this release was available?

**Comment by fbelter** [comment]
Ckan

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tjdeckard** [comment]
Interesting. I didn't expect CKAN to do that. I'm going to take this release down then. I recommend reverting to the previous version of USITools for now.

**Comment by MaxActionWang** [comment]
Hi @tjdeckard ,

I installed USI tools and Konstructions v112.0.1 from CKAN and loaded my previously saved checkpoint. It turned out that some parts from Konstructions (ie parts of the akita rover, which were unlocked in the research center) were not showing up in the VAB. Should I go back to v1.4.0? My game version is 1.12.5.3190. If you need any other info please lmk. Thanks!
